name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main  # သင်သုံးနေတဲ့ branch နာမည် (main သို့မဟုတ် master)
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOUR_PROJECT_NAME }}'
          channelId: live
          projectId: your-project-id
